# Generated by Django 3.1.4 on 2021-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=13)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
