# Generated by Django 3.1.4 on 2021-01-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postright'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='homeimage',
            field=models.ImageField(blank=True, max_length=300, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='hometitle',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to='media'),
        ),
    ]
