# Generated by Django 3.1.4 on 2021-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210112_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='homeimage',
        ),
        migrations.AddField(
            model_name='post',
            name='homeimage_one',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='homeimage_three',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='homeimage_two',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
