# Generated by Django 3.1.4 on 2021-01-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210112_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='homeimage_one',
            new_name='homeimage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='homeimage_three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='homeimage_two',
        ),
    ]
