# Generated by Django 3.1.4 on 2021-01-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210112_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='homecontent',
            field=models.TextField(blank=True),
        ),
    ]
