# Generated by Django 3.1.4 on 2021-01-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postright',
        ),
    ]
