# Generated by Django 3.1.4 on 2021-01-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_postright'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogcomment',
        ),
    ]
