# Generated by Django 3.1.4 on 2021-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogcomment_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
