# Generated by Django 3.1.4 on 2021-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
