# Generated by Django 3.1.4 on 2021-01-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepost_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepost',
        ),
    ]
