# Generated by Django 3.1.4 on 2021-01-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_homepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometitle', models.CharField(max_length=255)),
                ('homeimage', models.CharField(max_length=255)),
                ('homecontent', models.TextField(blank=True)),
                ('hometimestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
