# Generated by Django 3.1.4 on 2021-01-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homeblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homeblog',
        ),
    ]
